### ISSUE TITLE
How do I include subfolders

### ISSUE THREAD

**Issue by Oldenborg** [Smilefish2/laravel-mix-blade-pug#2]
I would be good to have an example of how to include subdirecorties. Say I have a directory structure like this
```
/src
    - index.pug
    /frontend
        - index.pug
        /articles
            - index.pug
```
How would i make that compile to
```
/src
    - index.blade.php
    /frontend
        - index.blade.php
        /articles
            - index.blade.php
```
Right now everything in the `articles`folder is ignored

Any help would be greatly appreciated, thanks :)

**Comment by Smilefish2** [comment]
Sorry, I'm busy at work.
You can try passing in a configuration parameter, such as:
```js
let mix = require('laravel-mix');
mix.pug = require('laravel-mix-blade-pug');

let pluginOptions = {
    search: '**/**/*.pug',
    ignore: ['**/node_modules/**/*', '**/components/**/*', '**/control/**/*', '**/_*.*'],
    pretty: true
}
mix.pug("./src", "./public",pluginOptions);
```

key point：
```js
search: '**/**/*.pug'
```
laravel-mix-blade-pug/src/config.js:
![image](https://user-images.githubusercontent.com/6111039/33411201-31a03ffc-d5bf-11e7-89c0-4dcc0b95f347.png)
